version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://dev_user:super_secret_password@db:5432/portfolio_db
      # Добавляем сюда:
      - RESEND_API_KEY=re_4p9eYen4_BCR2erXfpFCSq6C1vFLC5K5p
      - CONTACT_RECEIVER_EMAIL=vitalywu@icloud.com
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      # Папка 'postgres_data' сохранится на твоем Маке, даже если ты удалишь контейнер
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: